CREATE TABLE IF NOT EXISTS application (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    REDIRECT_URL TEXT,
    ALLOWED_DOMAINS TEXT,
    ORGANIZATION VARCHAR(255),
    CREATED_AT TIMESTAMP,
    CLIENT_KEY VARCHAR(255),
    CLIENT_SECRET TEXT,
);