version: "3.8"

services:
  app:
    container_name: nymeria
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    extra_hosts:
      - "localhost:127.0.0.1"    
    ports:
      - "8080:8080"