services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "kratos"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "kratos"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - nymeria-network
  app:
    container_name: nymeria-app
    build: .
    ports:
      - "9898:9898"
    depends_on:
      - db
      - kratos
    networks:
      - nymeria-network
  kratos-migrate:
    image: oryd/kratos:v1.3.1
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - nymeria-network
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.3.1
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    ports:
      - "4433:4433"
      - "4434:4434"
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos
    networks:
      - nymeria-network

volumes:
  db-data:
    name: nymeria-db
  kratos-sqlite:

networks:
  nymeria-network:
    name: nymeria-network
