version: "3"

services:
  db:
    container_name: nymeria-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: 
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: nymeria-app
    build: .
    ports:
      - "9898:9898"
    depends_on:
      - db
  kratos-migrate:
    image: oryd/kratos:v0.9.0-alpha.2
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:latest
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos

volumes:
  db-data:
    name: nymeria-db
  kratos-sqlite:
