version: v0.13.0

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://127.0.0.1:4434/

selfservice:
  default_browser_return_url: https://accounts.sdslabs.co/
  allowed_return_urls:
    - https://accounts.sdslabs.co/

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: sdslabs.co
      enabled: true

  flows:
    error:
      ui_url: https://accounts.sdslabs.co/error

    settings:
      ui_url: https://accounts.sdslabs.co/settings
      required_aal: highest_available
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: https://accounts.sdslabs.co/recovery
      use: code

    verification:
      enabled: true
      ui_url: https://accounts.sdslabs.co/verification
      use: code
      after:
        default_browser_return_url: https://accounts.sdslabs.co/welcome

    logout:
      after:
        default_browser_return_url: https://accounts.sdslabs.co/login

    login:
      ui_url: https://accounts.sdslabs.co/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://accounts.sdslabs.co/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri:
    from_address: 
    from_name:

feature_flags:
  use_continue_with_transitions: true
