selfservice:
    strategies:
      password:
        enabled: true
  
    settings:
      privileged_session_max_age: 20m
      after:
        profile:
          hooks:
            -
              hook: verify
  
    registration:
      request_lifespan: 10m
      after:
        password:
          hooks:
            -
              hook: session
            -
              hook: verify

identity:
    traits:
        default_schema_url: file:///etc/config/kratos/identity.schema.json
courier:
    smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

log:
    level: debug