selfservice:
    strategies:
      oidc:
        config:
          providers:
            - id: google # this is `<provider-id>` in the Authorization callback URL. DO NOT CHANGE IT ONCE SET!
              provider: google
              client_id: {{google.client_id}} # Replace this with the OAuth2 Client ID
              client_secret: {{google.client_secret}} # Replace this with the OAuth2 Client secret
              mapper_url: file:///etc/config/kratos/oidc.google.jsonnet
              # Alternatively, use an URL:
              # mapper_url: https://storage.googleapis.com/abc-cde-prd/9cac9717f007808bf17f22ce7f4295c739604b183f05ac4afb4
              scope:
                - email
                - profile
              # other supported scopes can be found in Google OAuth 2.0 dev docs
              requested_claims:
                id_token:
                  email:
                    essential: true
                  email_verified:
                    essential: true
                  given_name:
                    essential: true
                  family_name: null
                  hd: null # If you want the Google Workspace domain
        enabled: true
      password:
        enabled: true
  
    settings:
      privileged_session_max_age: 20m
      after:
        profile:
          hooks:
            -
              hook: verify
  
    registration:
      request_lifespan: 10m
      after:
        password:
          hooks:
            -
              hook: session
            -
              hook: verify

identity:
    traits:
        default_schema_url: file:///etc/config/kratos/identity.schema.json
courier:
    smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

log:
    level: debug