name: verify format & lint

on: [push,pull_request]

jobs:
  lint:
    name: linux64
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: './go.mod'

    - name: Install golangci lint
      run: make install-golangci-lint
    
    - name: Install goimports
      run: make install-goimports

    - name: Verify Format & Lint
      run: make verify
